<?php

/**
 * @file
 * Cavalla_webform module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_webform_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_webform':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme(). Lets us define our paragraphs templates in this module.
 */
function cavalla_webform_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_webform' => [
      'base hook' => 'paragraph',
    ],

  ];
}

/**
 *
 */
function cavalla_webform_preprocess_input__textfield(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

/**
 *
 */
function cavalla_webform_preprocess_input__submit(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

/**
 *
 */
function cavalla_webform_preprocess_input__email(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

/**
 *
 */
function cavalla_webform_preprocess_textarea(&$variables) {
  $variables['attributes']['class'][] = 'w-100';
}

/**
 *
 */
function cavalla_webform_preprocess_form_element_label(&$variables) {
  $variables['attributes']['class'] = 'form-check-label';
}

function cavalla_webform_preprocess_paragraph__cavalla_webform(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $variables['hide_webform'] = $paragraph->get('field_cavalla_webform_hide_wf')->value;
  $variables['hide_business_information'] = $paragraph->get('field_cavalla_webform_hide_')->value;
  $variables['hide_map'] = $paragraph->get('field_cavalla_webform_hide_map')->value;


  if ($variables['hide_business_information'] == 1 &&  $variables['hide_webform'] == 1) {
      $variables['col_width'] = 'w-100';
  }
  if ($variables['hide_webform'] == 1 ) {
      $variables['col_width'] = 'w-100';
  }
  else{
    $variables['col_width'] = 'w-50';
  }
}